/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#1b1c1c",
        "on-surface-variant": "#e3bebb",
        "outline": "#aa8986",
        "on-tertiary-fixed": "#1b1c1c",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-secondary-container": "#b5b5b5",
        "on-tertiary-fixed-variant": "#474746",
        "on-background": "#e5e2e1",
        "background": "#131313",
        "outline-variant": "#5a403e",
        "on-tertiary-container": "#f9f7f6",
        "error": "#ffb4ab",
        "on-primary": "#68000c",
        "primary-fixed": "#ffdad7",
        "on-tertiary": "#303030",
        "error-container": "#93000a",
        "secondary-fixed": "#e3e2e2",
        "surface-container-highest": "#353534",
        "surface-container": "#201f1f",
        "on-primary-fixed": "#410004",
        "surface-tint": "#ffb3ae",
        "primary": "#ffb3ae",
        "tertiary-fixed-dim": "#c8c6c5",
        "primary-container": "#d13639",
        "on-primary-fixed-variant": "#930015",
        "inverse-primary": "#b62129",
        "tertiary-fixed": "#e4e2e1",
        "inverse-on-surface": "#313030",
        "surface-container-low": "#1c1b1b",
        "tertiary": "#c8c6c5",
        "secondary-container": "#464747",
        "surface-container-high": "#2a2a2a",
        "secondary": "#c7c6c6",
        "surface": "#131313",
        "on-surface": "#e5e2e1",
        "surface-dim": "#131313",
        "surface-container-lowest": "#0e0e0e",
        "surface-bright": "#3a3939",
        "on-secondary": "#303031",
        "inverse-surface": "#e5e2e1",
        "tertiary-container": "#727171",
        "on-primary-container": "#fff4f3",
        "on-secondary-fixed-variant": "#464747",
        "primary-fixed-dim": "#ffb3ae",
        "secondary-fixed-dim": "#c7c6c6",
        "surface-variant": "#353534"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
